### PR TITLE
just a typo

### PR DESCRIPTION
**Pull request by stonekate**
and made some capital letters for consistency

### CODE REVIEW

**Comment by bnicenboim** [comment]
Thanks!
Can you rebuild the documentation as well? `devtools::document()` just to check that it passes without throwing errors

**Comment by stonekate** [comment]
I think it worked...

image

**Comment by bnicenboim** [comment]
I guess you need to commit the documentation and push it again so that it goes to this pull request

**Comment by stonekate** [comment]
oops... ok, now it seems to be there!

**Pull request merged**
